/**
Copyright 2021 ApiGear UG
Copyright 2021 Epic Games, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

////////////////////////////////
// WARNING AUTOGENERATED
// DO NOT MODIFY
///////////////////////////////

#include "TbSame2SameEnum2InterfaceSimulation.h"
#include "apig/TbSame2.json.adapter.h"
#include "ApiGear/Public/ApiGearConnectionManager.h"
#include "unrealsimulation.h"
#include "Async/Async.h"
#include "Engine/Engine.h"

using namespace ApiGear::JSONRPC;
UTbSame2SameEnum2InterfaceSimulationService::UTbSame2SameEnum2InterfaceSimulationService()
	: ITbSame2SameEnum2InterfaceInterface()
	, Prop1(ETbSame2Enum1::VALUE1)
	, Prop2(ETbSame2Enum2::VALUE1)
{
	UApiGearConnectionManager* AGCM = nullptr;
	if (GEngine != nullptr)
	{
		AGCM = GEngine->GetEngineSubsystem<UApiGearConnectionManager>();
	}
	NotifyRequestFunc SameEnum2InterfaceStateChangedFunc = [this](NotifyRequestArg arg)
	{
		const json fields = arg.params;
		if (fields.contains("prop1"))
		{
			if (Prop1 != fields["prop1"].get<ETbSame2Enum1>())
			{
				Prop1 = fields["prop1"].get<ETbSame2Enum1>();
				Execute_BroadcastProp1Changed(this, Prop1);
			}
		}
		if (fields.contains("prop2"))
		{
			if (Prop2 != fields["prop2"].get<ETbSame2Enum2>())
			{
				Prop2 = fields["prop2"].get<ETbSame2Enum2>();
				Execute_BroadcastProp2Changed(this, Prop2);
			}
		}
	};
	if (AGCM != nullptr)
	{
		AGCM->GetSimulationConnection()->Connect();
		AGCM->GetSimulationConnection()->onNotifyState("tb.same2/SameEnum2Interface", SameEnum2InterfaceStateChangedFunc);
	}

	CallResponseFunc GetSameEnum2InterfaceStateFunc = [this](CallResponseArg arg)
	{
		if (arg.result.size() != 1)
		{
			return;
		}
		const json fields = arg.result;
		if (fields.contains("prop1"))
		{
			if (Prop1 != fields["prop1"].get<ETbSame2Enum1>())
			{
				Prop1 = fields["prop1"].get<ETbSame2Enum1>();
				Execute_BroadcastProp1Changed(this, Prop1);
			}
		}
		if (fields.contains("prop2"))
		{
			if (Prop2 != fields["prop2"].get<ETbSame2Enum2>())
			{
				Prop2 = fields["prop2"].get<ETbSame2Enum2>();
				Execute_BroadcastProp2Changed(this, Prop2);
			}
		}
	};
	if (AGCM != nullptr)
	{
		AGCM->GetSimulationConnection()->doFetchState("tb.same2/SameEnum2Interface", GetSameEnum2InterfaceStateFunc);
	}

	// register notification callback functions, signal/event -> fcn
	NotifyRequestFunc sig1Func = [this](NotifyRequestArg arg)
	{
		const json fields = arg.params;
		if (fields.contains("param1"))
		{
			Execute_BroadcastSig1(this, fields["param1"].get<ETbSame2Enum1>());
		}
	};
	if (AGCM != nullptr)
	{
		AGCM->GetSimulationConnection()->onNotify("tb.same2/SameEnum2Interface#sig1", sig1Func);
	}

	NotifyRequestFunc sig2Func = [this](NotifyRequestArg arg)
	{
		const json fields = arg.params;
		if (fields.contains("param1") && fields.contains("param2"))
		{
			Execute_BroadcastSig2(this, fields["param1"].get<ETbSame2Enum1>(), fields["param2"].get<ETbSame2Enum2>());
		}
	};
	if (AGCM != nullptr)
	{
		AGCM->GetSimulationConnection()->onNotify("tb.same2/SameEnum2Interface#sig2", sig2Func);
	}
}

UTbSame2SameEnum2InterfaceSimulationService::~UTbSame2SameEnum2InterfaceSimulationService()
{
	if (GEngine != nullptr)
	{
		UApiGearConnectionManager* AGCM = GEngine->GetEngineSubsystem<UApiGearConnectionManager>();
		AGCM->GetSimulationConnection()->RemoveOnNotifyState("tb.same2/SameEnum2Interface");
		// unregister notification callback functions
		AGCM->GetSimulationConnection()->RemoveOnNotify("tb.same2/SameEnum2Interface#sig1");
		AGCM->GetSimulationConnection()->RemoveOnNotify("tb.same2/SameEnum2Interface#sig2");
	}
}

void UTbSame2SameEnum2InterfaceSimulationService::BroadcastSig1_Implementation(const ETbSame2Enum1& Param1)
{
	Sig1Signal.Broadcast(Param1);
}

FTbSame2SameEnum2InterfaceSig1Delegate& UTbSame2SameEnum2InterfaceSimulationService::GetSig1SignalDelegate()
{
	return Sig1Signal;
}

void UTbSame2SameEnum2InterfaceSimulationService::BroadcastSig2_Implementation(const ETbSame2Enum1& Param1, const ETbSame2Enum2& Param2)
{
	Sig2Signal.Broadcast(Param1, Param2);
}

FTbSame2SameEnum2InterfaceSig2Delegate& UTbSame2SameEnum2InterfaceSimulationService::GetSig2SignalDelegate()
{
	return Sig2Signal;
}

void UTbSame2SameEnum2InterfaceSimulationService::BroadcastProp1Changed_Implementation(const ETbSame2Enum1& InProp1)
{
	Prop1 = InProp1;
	Prop1Changed.Broadcast(InProp1);
}

ETbSame2Enum1 UTbSame2SameEnum2InterfaceSimulationService::GetProp1_Implementation() const
{
	return Prop1;
}

void UTbSame2SameEnum2InterfaceSimulationService::SetProp1_Implementation(const ETbSame2Enum1& InProp1)
{
	Params params;
	params["prop1"] = InProp1;
	if (GEngine != nullptr)
	{
		UApiGearConnectionManager* AGCM = GEngine->GetEngineSubsystem<UApiGearConnectionManager>();
		AGCM->GetSimulationConnection()->doCall("tb.same2/SameEnum2Interface", "_set", params);
	}
}

FTbSame2SameEnum2InterfaceProp1ChangedDelegate& UTbSame2SameEnum2InterfaceSimulationService::GetProp1ChangedDelegate()
{
	return Prop1Changed;
}

void UTbSame2SameEnum2InterfaceSimulationService::BroadcastProp2Changed_Implementation(const ETbSame2Enum2& InProp2)
{
	Prop2 = InProp2;
	Prop2Changed.Broadcast(InProp2);
}

ETbSame2Enum2 UTbSame2SameEnum2InterfaceSimulationService::GetProp2_Implementation() const
{
	return Prop2;
}

void UTbSame2SameEnum2InterfaceSimulationService::SetProp2_Implementation(const ETbSame2Enum2& InProp2)
{
	Params params;
	params["prop2"] = InProp2;
	if (GEngine != nullptr)
	{
		UApiGearConnectionManager* AGCM = GEngine->GetEngineSubsystem<UApiGearConnectionManager>();
		AGCM->GetSimulationConnection()->doCall("tb.same2/SameEnum2Interface", "_set", params);
	}
}

FTbSame2SameEnum2InterfaceProp2ChangedDelegate& UTbSame2SameEnum2InterfaceSimulationService::GetProp2ChangedDelegate()
{
	return Prop2Changed;
}

ETbSame2Enum1 UTbSame2SameEnum2InterfaceSimulationService::Func1_Implementation(const ETbSame2Enum1& Param1)
{
	Params params;
	params["param1"] = Param1;
	TPromise<ETbSame2Enum1> Promise;
	Async(EAsyncExecution::Thread,
		[params, &Promise]()
		{
			CallResponseFunc GetSameEnum2InterfaceStateFunc = [&Promise](CallResponseArg arg)
			{ Promise.SetValue(arg.result.get<ETbSame2Enum1>()); };
			if (GEngine != nullptr)
			{
				UApiGearConnectionManager* AGCM = GEngine->GetEngineSubsystem<UApiGearConnectionManager>();
				AGCM->GetSimulationConnection()->doCall("tb.same2/SameEnum2Interface", "func1", params, GetSameEnum2InterfaceStateFunc);
			}
		});

	return Promise.GetFuture().Get();
}

ETbSame2Enum1 UTbSame2SameEnum2InterfaceSimulationService::Func2_Implementation(const ETbSame2Enum1& Param1, const ETbSame2Enum2& Param2)
{
	Params params;
	params["param1"] = Param1;
	params["param2"] = Param2;
	TPromise<ETbSame2Enum1> Promise;
	Async(EAsyncExecution::Thread,
		[params, &Promise]()
		{
			CallResponseFunc GetSameEnum2InterfaceStateFunc = [&Promise](CallResponseArg arg)
			{ Promise.SetValue(arg.result.get<ETbSame2Enum1>()); };
			if (GEngine != nullptr)
			{
				UApiGearConnectionManager* AGCM = GEngine->GetEngineSubsystem<UApiGearConnectionManager>();
				AGCM->GetSimulationConnection()->doCall("tb.same2/SameEnum2Interface", "func2", params, GetSameEnum2InterfaceStateFunc);
			}
		});

	return Promise.GetFuture().Get();
}
